# Stack configuration file for RuneScript Spell Checker

resolver: lts-22.28  # GHC 9.6.5

packages:
- .

extra-deps: []

# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []

# Control whether we use the GHC we find on the path
system-ghc: false

# Require a specific version of stack, using version ranges
# require-stack-version: -any # Default
# require-stack-version: ">=2.13"

# Override the architecture used by stack, especially useful on Windows
# arch: i386
# arch: x86_64

# Extra directories used by stack for building
# extra-include-dirs: [/path/to/dir]
# extra-lib-dirs: [/path/to/dir]

# Allow a newer minor version of GHC than the snapshot specifies
# compiler-check: newer-minor

# Build configuration
build:
  # Enable optimizations for production builds
  optimization: true
  
  # Enable warnings
  pedantic: true
  
  # Haddock documentation
  haddock: false
  
  # Copy executables to a central location
  copy-bins: true
  
  # Install location for executables
  install-exe: true

# Development settings
develop: false

# Test configuration
test:
  # Additional arguments for test suite
  additional-args: []
  
  # Enable test coverage
  coverage: false
  
  # No run tests for dependencies
  no-run-tests: false

# Benchmark configuration
benchmark:
  # Additional arguments for benchmarks
  additional-args: []

# Docker configuration (optional)
# docker:
#   enable: false
#   repo: "fpco/stack-build"

# Nix configuration (optional)
# nix:
#   enable: false
#   packages: [zlib]

# Global project settings
save-hackage-creds: false

# Modify compiler arguments
ghc-options:
  # Apply to all local packages
  "$locals": -Wall -Wcompat -Widentities -Wincomplete-record-updates -Wincomplete-uni-patterns -Wmissing-home-modules -Wpartial-fields -Wredundant-constraints
  
  # Apply to specific package
  spell-checker: -threaded -rtsopts -with-rtsopts=-N

# Setup.hs script configuration
setup-info-locations: []

# Snapshot location (can be a URL or local path)
# snapshot-location-base: https://example.com/snapshots

# Allow newer versions of dependencies
# allow-newer: true

# Configure package indices
package-indices:
- download-prefix: https://hackage.haskell.org/
  hackage-security:
    keyids:
    - 0a5c7ea47cd1b15f01f5f51a33adda7e655bc0f0b0615baa8e271f4c3351e21d
    - 1ea9ba32c526d1cc91ab5e5bd364ec5e9e8cb67179a471872f6e26f0ae773d42
    - 280b10153a522681163658cb49f632cde3f38d768b736ddbc901d99a1a772833
    - 2a96b1889dc221c17296fcc2bb34b908ca9734376f0f361660200935916ef201
    - 2c6c3627bd6c982990239487f1abd02e08a02e6cf16edb105a8012d444d870c3
    - 51f0161b906011b52c6613376b1ae937670da69322113a246a09f807c62f6921
    - 772e9f4c7db33d251d5c6e357b4ca30d5f24c0d4853b85822b4388c86fcc7bef
    - aa315286e6ad281ad61182235533c41e806e5a787e0b6d1e7eef3f09d137d2e9
    - fe331502606802feac15e514d9b9ea83fee8b6ffef71335479a2e68d84adc6b0
    key-threshold: 3
    ignore-expiry: false
